annotations:
  category: Infrastructure
  images: |
    - name: seaweedfs
      image: docker.io/kubeshop/testkube-seaweedfs:4.23
  licenses: Apache-2.0
apiVersion: v2
appVersion: "4.23"
dependencies:
  - name: seaweedfs
    version: 4.22.0
    repository: https://seaweedfs.github.io/seaweedfs/helm
description: Testkube helm chart to deploy SeaweedFS as an S3-compatible storage backend.
maintainers:
- name: Testkube
  email: support@testkube.io
  url: https://github.com/kubeshop/testkube-thirdparty-artifacts
name: seaweed
sources:
- https://github.com/kubeshop/testkube-thirdparty-artifacts/tree/main/seaweed
- https://github.com/seaweedfs/seaweedfs
version: 4.23-0
