# SeaweedFS Service Configuration
name: seaweed
display_name: SeaweedFS
source: dockerhub
source_image: chrislusf/seaweedfs
version_pattern: "^[0-9]+\\.[0-9]+$"
dockerfile: seaweedfs-release.dockerfile
dockerhub_image: docker.io/kubeshop/testkube-seaweedfs
gar_image: us-east1-docker.pkg.dev/testkube-cloud-372110/testkube/seaweed
